### ISSUE TITLE
Setting Up .env Variables and Backend Deployment Options

### ISSUE THREAD

**Issue by novanmartejares** [Miruro-no-kuon/Miruro#167]
What are the exact data that i will put in .env.?
sorry for my question. i just want to know where to find it like what website.

**Comment by akionii** [comment]
Hey!

Thanks for reaching out! Let’s get those `.env` variables sorted out. 

- **VITE_BACKEND_URL**: The one we provided (`https://api.consumet.org/`) should work, but if it’s down or you wanna use your own, feel free. Also, if you don’t want to deploy your own instance, hang tight! We’ll be deploying a public version of our backend shortly. Stay updated through our Discord at: https://discord.gg/4kfypZ96K4.

- **VITE_API_KEY**: Not in use right now, so no worries there.

- **VITE_PROXY_URL**: Just keep it as `https://corsproxy.io`. It’ll do the trick for CORS stuff.

- **VITE_IS_LOCAL & VITE_LOCAL_IP**: These depend on your setup. Usually, you won't need to change them.

- **PORT**: This is for your server's port. Stick with the default if you're unsure.

### Deploying Your Own Backend:

If `api.consumet.org` isn’t working for you, or you just want your own setup, deploying your backend is super simple:

1. Go to the [Consumet API on GitHub](https://github.com/consumet/api.consumet.org). There's a **"Deploy"** button in the README. Hit it, and Vercel will take it from there. No need to fork the repo.
   
2. If you’re not on Vercel yet, you’ll need to sign up. Follow the steps, and you’ll have your backend running in no time.

3. Update the `VITE_BACKEND_URL` in your `.env` with the new link Vercel gives you.

Hope this helps! Let me know if you have any more questions or need more help.

Cheers.

**Comment by novanmartejares** [comment]
thank you very much for this. such a big help
