### ISSUE TITLE
[Bug]: ERROR: Error fetching data: Network Error

### ISSUE THREAD

**Issue by chirag12888** [Miruro-no-kuon/Miruro#192]
### What went wrong?

website is opening with no error but data of the episodes are not loading 

### How'd you stumble upon it?

when i run the program,  in the the browser error is coming 

![image](https://github.com/Miruro-no-kuon/Miruro/assets/138520615/15f41957-ed13-4e80-94b1-df7fab6f7ff9)
![image](https://github.com/Miruro-no-kuon/Miruro/assets/138520615/c22ac3e6-ac79-4a0d-bcbd-3ea74965c242)

### What you hoped for vs. What actually happened

i just run the program and error cam plz check the ss

### Which version was acting up?

0.4.2

### Which browsers were a bummer?

Microsoft Edge

### Code of Conduct Agreement

- [X] I agree to follow this project's Code of Conduct.

**Comment by techroy23** [comment]
Please check this https://github.com/Miruro-no-kuon/Miruro/issues/170
