### ISSUE TITLE
Proxy path enforcement `/api/json`

### ISSUE THREAD

**Issue by skgupta507** [Miruro-no-kuon/Miruro#195]
hello @akionii @trying559 i hosted an instance of the site but i ran into an issue after deploying it 
it says **ERROR: An unexpected error occurred** after watching the tutorial this was not fixed could u help me with this issue.
![image](https://github.com/Miruro-no-kuon/Miruro/assets/131786207/1777963a-f4c4-40b6-940b-b3ee47b261a9)

**Comment by trying559** [comment]
Hi, It seems the CORS proxy provided in the .env file may be blocked in certain countries. Consider using an alternative CORS proxy service accessible from your deployment location to resolve the issue.

**Comment by skgupta507** [comment]
hi @trying559 sorry for disturbing you but i tried 7 other proxy services it is working fine on other projects but even after deplying with those the issue doesnot seem to work. what else can i do to resolve this issue iam from india b the way if it helps. to pinpoint a solution.

**Comment by techroy23** [comment]
Can you open F12 (console log) and check how the URL is being queried since some cors may have different URI SCHEME.

**Comment by skgupta507** [comment]
hey @techroy23  iam currently using this proxy [https://animedexproxy.sunilk98850.workers.dev/]  
after opening the console log this is the error i found. screenshot attached below.
![image](https://github.com/Miruro-no-kuon/Miruro/assets/131786207/001741b7-25c8-4ca8-b7ef-eed73be7b818)

**Comment by techroy23** [comment]
Similar to #170.

**Comment by akionii** [comment]
Hey there! 

I've decided to reopen issue #170 since it's been catching the eye of some newcomers on the project. So, @skgupta507, I did a bit of digging into the proxy you're using (https://animedexproxy.sunilk98850.workers.dev/), and here's what I found:

```
Cors Proxy Is Working

Usage: https://proxy.techzbots1.workers.dev/?u=https://example.com
```

Looks like the issue isn't about the proxies getting blocked, but rather, we're forcing a `/api/json?url=...` path instead of the `/?u=...` that your `proxy.techzbots1.workers.dev` worker proxy requires. This could happen with any proxy. 

So, I'm keeping this issue open as well, since I just noticed this problem with the proxy path enforcement.

**Comment by skgupta507** [comment]
Hi @akionii so do we need to change something in the proxy code or ur going to provide us with some other solution like modifying the projects code.

**Comment by akionii** [comment]
Hey @skgupta507, just hang in there for a bit. We're on it,  we've found a ton of ways to fix it. But alongside that, we've got a bunch of other updates and stuff coming too. So right now we're weighing everything for _convenience, performance, and speed_. We'll keep you posted once it's sorted. **Thanks for your patience!**

**Comment by techroy23** [comment]
@skgupta507 You may test the current build now. I got it working without using any corsproxy. let us know if you encounter any errors.

**Comment by anixplay9** [comment]
![Screenshot (84)](https://github.com/Miruro-no-kuon/Miruro/assets/173687023/bfa2b925-6651-4abc-8472-49428cdcb145)
