### ISSUE TITLE
New Episodes Not Updating

### ISSUE THREAD

**Issue by anitummy** [Miruro-no-kuon/Miruro#197]
### What went wrong?

New episodes aren't adding 

### How'd you stumble upon it?

All working great 

### What you hoped for vs. What actually happened

You are the best 

### Anything else we should know?

Nope 

### How can we reach you? (Totally Optional)

mu7hunter@gmail.com

### Which version was acting up?

0.4.2

### Which browsers were a bummer?

Chrome

### Got logs?

```shell
Okay
```

### Code of Conduct Agreement

- [x] I agree to follow this project's Code of Conduct.

**Comment by techroy23** [comment]
Can you provide the name or the anime or the anime ID.

**Comment by trying559** [comment]
Hi @anitummy 
Thanks for reaching out and bringing up the issue you're facing. Before diving into addressing it, I want to kindly remind you of the project's license and rules, as outlined in our [README](https://github.com/Miruro-no-kuon/Miruro/blob/preview-main/README.md) file.

Our project follows a [Custom BY-NC License](https://github.com/Miruro-no-kuon/Miruro/blob/preview-main/LICENSE), which means it's intended for non-commercial use only. Additionally, it's crucial to provide clear credit to our platform, miruro.com, when deploying the project. Upon reviewing your deployment at https://www.anitummy.com/, I noticed that it currently lacks the necessary credit.

Respecting these guidelines helps maintain the integrity of the project and ensures that everyone benefits from it within the permitted usage. Could you please update your deployment to include the appropriate credit to miruro.com? Once that's done, I'll be more than happy to assist you with the issue you've encountered.

**Comment by akionii** [comment]
> [!IMPORTANT]
> Closing this issue due to a lack of **response or activity**. It will remain **pending/closed** until someone reopens with updated information or a response
